import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "./providers";
import { AppbarClient } from "./AppbarClient";
import jwt from "jsonwebtoken";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = jwt.sign({ id: "luffy" }, "secret");
  return (
    <html lang="en">
      <body>
        <Provider token={token}>
          <AppbarClient />
          {children}
        </Provider>
      </body>
    </html>
  );
}
